<?php

declare(strict_types=1);

/**
 * Build script that generates a single-file PHP distribution.
 *
 * The generated file (dist/libcnpj.php) contains all library classes
 * without namespaces, so it can be used in projects that do not use Composer.
 *
 * Composer users should prefer vendor/autoload.php and the LibCnpj\ namespace.
 */

$sourceDirectory = __DIR__ . '/src';
$distDirectory = __DIR__ . '/dist';
$distFile = $distDirectory . '/libcnpj.php';

$files = [
    'Cnpj.php',
    'CnpjValidator.php',
    'CnpjFormatter.php',
];

$parts = [];

foreach ($files as $file) {
    $path = $sourceDirectory . '/' . $file;
    $content = file_get_contents($path);

    if ($content === false) {
        throw new RuntimeException('Could not read ' . $path);
    }

    $parts[] = extractClassBody($content);
}

$concatenated = implode(PHP_EOL . PHP_EOL, $parts);

$header = <<<'HEADER'
<?php

declare(strict_types=1);

/**
 * lib-cnpj single-file distribution.
 *
 * Generated automatically by php/build.php.
 * Do not edit this file directly; change the files in php/src/ instead.
 *
 * Usage:
 *   require 'path/to/dist/libcnpj.php';
 *   var_dump(Cnpj::isValid('11.222.333/0001-81'));
 *
 * For Composer-based projects, use vendor/autoload.php and the LibCnpj\ namespace.
 */

HEADER;

if (is_dir($distDirectory) === false) {
    mkdir($distDirectory, 0755, true);
}

$written = file_put_contents($distFile, $header . $concatenated);

if ($written === false) {
    throw new RuntimeException('Could not write ' . $distFile);
}

printf("Generated: %s (%d bytes)%s", $distFile, $written, PHP_EOL);

function extractClassBody(string $content): string
{
    $content = preg_replace('/^\s*<\?php\s*/', '', $content);
    $content = preg_replace('/\s*declare\s*\(\s*strict_types\s*=\s*1\s*\)\s*;\s*/', '', $content);
    $content = preg_replace('/\s*namespace\s+LibCnpj\s*;\s*/', '', $content);

    return trim($content);
}
